# Generated by Django 3.1.1 on 2020-09-22 03:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0003_auto_20200919_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опублековать')),
            ],
            options={
                'verbose_name': 'Категори',
                'verbose_name_plural': 'Категория',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(max_length=100, verbose_name='Удобства')),
            ],
            options={
                'verbose_name': 'Удобства',
                'verbose_name_plural': 'Удобства',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Загаловак')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('district', models.CharField(blank=True, max_length=200, verbose_name='Район')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('rooms', models.IntegerField(default=0, verbose_name='Комнат')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Состояние')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.CharField(max_length=200, verbose_name='цена')),
                ('bedrooms', models.IntegerField(blank=True, default=0, verbose_name='спальни')),
                ('bathrooms', models.IntegerField(blank=True, default=0, verbose_name='ванные комнаты')),
                ('garage', models.IntegerField(default=0, verbose_name='гараж')),
                ('floors', models.IntegerField(default=0, verbose_name='Этажи')),
                ('sqft', models.IntegerField(default=0, verbose_name='Квадратные метры')),
                ('land_area', models.IntegerField(default=0, verbose_name='площадь участка')),
                ('terrace_area', models.IntegerField(default=0, verbose_name='площадь террасы')),
                ('lot_size', models.CharField(max_length=200, verbose_name='номер ID')),
                ('vid_name', models.CharField(blank=True, help_text='Вид недвижимости на пример новострой', max_length=100, verbose_name='вид')),
                ('tip_name', models.CharField(blank=True, help_text='Тип недвижимость', max_length=100, verbose_name='Тип')),
                ('sale_and_rental', models.CharField(blank=True, help_text='Продажа или аренда', max_length=100, verbose_name='Для')),
                ('from_the_sea', models.IntegerField(blank=True, default=0, help_text='если не нужно отмечать сколько от моря оставьте <<ноль>>', verbose_name='от моря')),
                ('photo_main', models.ImageField(upload_to='photos-home/%Y/%m/%d/', verbose_name='карточтка товара')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Контакт')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.category', verbose_name='Категория')),
                ('page_info', models.ManyToManyField(blank=True, help_text='Что есть в доме', to='listings.Info', verbose_name='Удобства')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
            options={
                'verbose_name': 'Объявления',
                'verbose_name_plural': 'Объявлени',
                'db_table': 'listing',
            },
        ),
        migrations.CreateModel(
            name='Galary_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galary_image', models.ImageField(blank=True, upload_to='photos-home/%Y/%m/%d/', verbose_name='Картинка')),
                ('Listing_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
            options={
                'verbose_name': 'Галирея',
                'verbose_name_plural': 'Галиреи',
                'db_table': 'galary_image',
            },
        ),
    ]
