# Generated by Django 3.1.1 on 2020-09-22 03:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254)),
                ('nomer', models.CharField(max_length=100, verbose_name='Номер ID')),
                ('telephone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('text', models.TextField(verbose_name='Сообщения')),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.listing')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
